myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/urls.py
from django.urls import path, include
from . import views
from .forms import SignupForm, CreateGoalForm

urlpatterns = [
    path('', views.get_grading_parameters),
    path('movegoal/<int:goal_id>', views.move_goal, name="move_goal"),
    path('addgoal', views.add_goal),
    path('home', views.home, name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register', views.register, name="registration"),
    path('addgoal', views.add_goal, name="AddGoal"),
    #path('movegoal', views.move_goal, name="MoveGoal"),
    path('success_message', views.success_page, name="success_message"),
]

app_name = 'olaoyejnrscrumy'
#app_name = 'accounts'

myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('olaoyejnrscrumy/', include('olaoyejnrscrumy.urls', namespace='olaoyejnrscrumy')),
    path('websocket/', include('websocket.urls')),
]

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm

# Create your models here.

class GoalStatus(models.Model):
    status_name = models.CharField(max_length=300)

    def __str__(self):
        return self.status_name

class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=200)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length=300)
    moved_by = models.CharField(max_length=300)
    owner = models.CharField(max_length=100)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='users')

    def __str__(self):
        return self.goal_name

class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=200)
    created_by = models.CharField(max_length=300)
    moved_from = models.CharField(max_length=200)
    moved_to = models.CharField(max_length=200)
    time_of_action = models.TimeField()
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by




       

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import ScrumyGoals, GoalStatus
class SignupForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget= forms.PasswordInput)
    class Meta:
        model = User
        fields = ['first_name','last_name', 'email','username','password']


class CreateGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user', 'goal_status']


class DevCreateGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user', 'goal_status']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['goal_status'].queryset = GoalStatus.objects.filter(status_name='Weekly Goal')
        self.fields['user'].queryset = User.objects.filter(username = user.username)

class MoveGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status']

class DevMoveGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['goal_status'].queryset = GoalStatus.objects.exclude(status_name='Done Goal')

class QAMoveGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['goal_status'].queryset = GoalStatus.objects.filter(status_name='Done Goal')

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User, Group
from .models import ScrumyGoals,ScrumyHistory,GoalStatus
from random import randint
from .forms import SignupForm, CreateGoalForm, MoveGoalForm, DevMoveGoalForm, QAMoveGoalForm, DevCreateGoalForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def get_grading_parameters(request):
    new_message = ScrumyGoals.objects.filter(goal_name="Learn Django")[0].goal_name
    return HttpResponse(new_message)

@login_required
def move_goal(request, goal_id):
    
    # except Exception as e:
    #     return render(request, 'olaoyejnrscrumy/exception.html', {'error': 'A record with that goal id does not exist'})
    #return HttpResponse(target.goal_name)
    current_user = request.user
    user_group = current_user.groups.all()[0].name
    Dev = Group.objects.get(name = 'Developer').name
    QA = Group.objects.get(name = 'Quality Assurance').name
    Admin = Group.objects.get(name = 'Admin').name
    Owner = Group.objects.get(name = 'Owner').name

    scrumy_goals = get_object_or_404(ScrumyGoals, goal_id=goal_id)

    if user_group == Admin or user_group == Owner:
        if request.method == 'POST':
            form = MoveGoalForm(request.POST)
            if form.is_valid():
                #scrumygoals = form.save(commit=False)
                scrumy_goals.goal_status = form.cleaned_data['goal_status']
                #cur_goal = ScrumyGoals.objects.get(goal_id = goal_id)
                #cur_goal.goal_status = form.cleaned_data['status_name']
                #scrumygoals.goal_id = gen_num()
                scrumy_goals.save()
                return redirect('/olaoyejnrscrumy/home')
        else:
            form = MoveGoalForm()
            args = {'form':form, 'current_user':current_user}
            return render(request, 'olaoyejnrscrumy/movegoal.html', args)  
    elif user_group == Dev and current_user == scrumy_goals.user:
        if request.method == 'POST':
            form = DevMoveGoalForm(request.POST)
            if form.is_valid():
                scrumy_goals.goal_status = form.cleaned_data['goal_status']
                scrumy_goals.save()
                return redirect('/olaoyejnrscrumy/home')
        else:
            form = DevMoveGoalForm()
            args = {'form':form, 'current_user':current_user}
            return render(request, 'olaoyejnrscrumy/movegoal.html', args)
    elif user_group == Dev and current_user != scrumy_goals.user:
        return render(request, 'olaoyejnrscrumy/denied.html')
        #return render(request, 'olaoyejnrscrumy/movegoal.html')

    elif user_group == QA and scrumy_goals.goal_status.status_name == 'Verify Goal':
        if request.method == 'POST':
            form = QAMoveGoalForm(request.POST)
            if form.is_valid():
                scrumy_goals.goal_status = form.cleaned_data['goal_status']
                scrumy_goals.save()
                return redirect('/olaoyejnrscrumy/home')
        else:
            form = QAMoveGoalForm()
            args = {'form':form, 'current_user':current_user}
            return render(request, 'olaoyejnrscrumy/movegoal.html', args)

    elif user_group == QA and current_user == scrumy_goals.user:
        if request.method == 'POST':
            form = MoveGoalForm(request.POST)
            if form.is_valid():
                scrumy_goals.goal_status = form.cleaned_data['goal_status']
                scrumy_goals.save()
                return redirect('/olaoyejnrscrumy/home')
        
        else:
            form = MoveGoalForm()
            args = {'form':form, 'current_user':current_user}
            return render(request, 'olaoyejnrscrumy/movegoal.html', args)


    elif user_group == QA and scrumy_goals.goal_status.status_name != 'Verify Goal':
        return render(request, 'olaoyejnrscrumy/QAdenied.html')



def gen_num():
    not_unique = True
    while not_unique:
        num = randint(1000,9999)
        not_unique = ScrumyGoals.objects.filter(goal_id=num).exists()
    return num


@login_required
def  add_goal(request):
    current_user = request.user
    user_group = current_user.groups.all()[0].name
    Dev = Group.objects.get(name = 'Developer').name
    QA = Group.objects.get(name = 'Quality Assurance').name
    Admin = Group.objects.get(name = 'Admin').name
    Owner = Group.objects.get(name = 'Owner').name
    if user_group == Dev or QA:
        if request.method == 'POST':
            form = DevCreateGoalForm(request.user, request.POST)
            if form.is_valid():
                scrumygoals = form.save(commit=False)
                scrumygoals.user = form.cleaned_data['user']
                scrumygoals.goal_name = form.cleaned_data['goal_name']
                scrumygoals.goal_status = form.cleaned_data['goal_status']
                scrumygoals.goal_id = gen_num()
                #ScrumyGoals.objects.create(goal_name=form.cleaned_data['goal_name'], goal_id=gen_num(),goal_status= form.cleaned_data['goal_status'], user=form.cleaned_data['user'])
                scrumygoals.save()
                return redirect('/olaoyejnrscrumy/home')
        else:
            form = DevCreateGoalForm(request.user)
            args = {'form':form}
            return render(request, 'olaoyejnrscrumy/addgoal.html', args)
    return render(request, 'olaoyejnrscrumy/addgoal.html')
@login_required
def home(request):
    # record_list = ScrumyGoals.objects.get(goal_name = 'Learn Django')
    # context = {'goal_name': record_list.goal_name, 'goal_id': record_list.goal_id, 'user': record_list.user}
    
    All_Users = User.objects.all()
    wikly_goals = GoalStatus.objects.filter(status_name = "Weekly Goal")
    All_weekly_goals = [goals.scrumygoals_set.all() for goals in wikly_goals][0]
    #All_weekly_goals = wikly_goals.scrumygoals_set.all()

    daily_goals = GoalStatus.objects.filter(status_name = "Daily Goal")
    All_daily_goals =  [goals.scrumygoals_set.all() for goals in daily_goals][0]

    veri_goals = GoalStatus.objects.filter(status_name = "Verify Goal")
    All_veri_goals = [goals.scrumygoals_set.all() for goals in veri_goals][0]

    done_goals = GoalStatus.objects.filter(status_name = "Done Goal")
    All_done_goals = [goals.scrumygoals_set.all() for goals in done_goals][0]

    user = request.user
    rank = user.groups.all()[0].name

    Contexts = {'rank': rank, 'All_Users': All_Users, 'All_weekly_goals': All_weekly_goals, "All_daily_goals": All_daily_goals, "All_veri_goals": All_veri_goals, "All_done_goals": All_done_goals}

    return render(request, 'olaoyejnrscrumy/home.html', Contexts)

def success_page(request):
    return render(request, 'olaoyejnrscrumy/message.html')

def register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data['password']
            )
            new_user.save()
            dev_group = Group.objects.get(name='Developer')
            dev_group.user_set.add(new_user)
            return redirect('/olaoyejnrscrumy/success_message')
    else:
        form = SignupForm()

        args = {'form':form}
        return render(request, 'registration/index.html', args)

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/QAdenied.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Denied</title>
</head>
<body>
    <h1>you dont have the permission to change goals of this type</h1>
</body>
</html>

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Goal</title>
</head>
<body>

    <div>
        <h1>Create a Goal</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create</button>
        </form>
    </div>
    
</body>
</html>

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/denied.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Denied</title>
</head>
<body>
    <h1>you dont have the permission to change another persons goal</h1>
    <h3>
        <a href="{% url 'olaoyejnrscrumy:home' %}"> Go To Home Page </a>
    </h3>
</body>
</html>

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {{error}}
</body>
</html>

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/home.html
<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;border-color:#aabcfe;}
    .tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#aabcfe;color:#669;background-color:#e8edff;}
    .tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#aabcfe;color:#039;background-color:#b9c9fe;}
    .tg .tg-hmp3{background-color:#D2E4FC;text-align:left;vertical-align:top}
    .tg .tg-baqh{text-align:center;vertical-align:top}
    .tg .tg-mb3i{background-color:#D2E4FC;text-align:right;vertical-align:top}
    .tg .tg-lqy6{text-align:right;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
    </style>

    <h3>
        <a href="{% url 'olaoyejnrscrumy:AddGoal' %}"> Go To Add Goals Page </a>
   </h3>
   <h1>Logged in as: {{user}}</h1>

   <h1>Designation: {{rank}}</h1>
    <table class="tg">
      <tr>
        <th scope="col" class="tg-hmp3"><h2>User</h2></td>
        <th scope="col" class="tg-hmp3"><h2>Weekly Goals</h2></td>
        <th scope="col" class="tg-hmp3"><h2>Daily Goals</h2></td>
        <th scope="col" class="tg-hmp3"><h2>Verify Goals</h2></td>
        <th scope="col" class="tg-hmp3"><h2>Done Goals</h2></td>
      </tr>
      {% for user in All_Users %}
        <tr>
            <td class="tg-0lax"><h2>{{user}}</h2></td>
            <td class="tg-0lax">
                {% for tasks in user.users.all %}
                    {% if tasks in All_weekly_goals %}
                    <h1>{{tasks.goal_name}} - ({{tasks.goal_id}})
                        <br>
                        {% if tasks.goal_name %}
                            <a href="{% url 'olaoyejnrscrumy:move_goal' tasks.goal_id %}">
                                <input type="button" value="move goal">
                            </a>                
                        {% endif %}
                        <br>
                    </h1>
                    {% endif %}
                {% endfor %}
            </td>
            <td class="tg-0lax">
                {% for tasks in user.users.all %}
                    {% if tasks in All_daily_goals %}
                        <h1>{{tasks.goal_name}} - ({{tasks.goal_id}})
                        <br>
                        {% if tasks.goal_name %}                          
                            <a href="{% url 'olaoyejnrscrumy:move_goal' tasks.goal_id %}">
                                <input type="button" value="move goal">
                            </a>
                        {% endif %}
                        <br>
                    </h1>
                    {% endif %}
                {% endfor %}
            </td>
            <td class="tg-0lax">
                    {% for tasks in user.users.all %}
                        {% if tasks in All_veri_goals %}
                        <h1>{{tasks.goal_name}} - ({{tasks.goal_id}})
                            <br>
                            {% if tasks.goal_name %}                          
                                <a href="{% url 'olaoyejnrscrumy:move_goal' tasks.goal_id %}">
                                    <input type="button" value="move goal">
                                </a>
                            {% endif %}
                            <br>
                            </h1>
                        {% endif %}
                    {% endfor %}
            </td>
            <td class="tg-0lax">
                    {% for tasks in user.users.all %}
                        {% if tasks in All_done_goals %}
                        <h1>{{tasks.goal_name}} - ({{tasks.goal_id}})
                            <br>
                            {% if tasks.goal_name %}                          
                                <a href="{% url 'olaoyejnrscrumy:move_goal' tasks.goal_id %}">
                                    <input type="button" value="move goal">
                                </a>
                            {% endif %}
                            <br>
                        </h1>
                        {% endif %}
                    {% endfor %}
            </td>
        
        </tr>
      {% endfor %}
      <!-- <tr>
        <td class="tg-hmp3">2</td>
        <td class="tg-hmp3">Running</td>
        <td class="tg-mb3i">15:30</td>
        <td class="tg-mb3i">14:10</td>
        <td class="tg-mb3i">15:45</td>
      </tr>
      <tr>
        <td class="tg-0lax">3</td>
        <td class="tg-0lax">Shooting</td>
        <td class="tg-lqy6">70%</td>
        <td class="tg-lqy6">55%</td>
        <td class="tg-lqy6">90%</td>
      </tr> -->
    </table>

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Voila</title>
</head>
<body>
    <h3>
        <a href="{% url 'olaoyejnrscrumy:home' %}"> Go To Home Page </a>
    </h3>

    <h1>Your account has been created successfully</h1>
</body>
</html>

myscrumy/Django-olaoyejnrscrumy/olaoyejnrscrumy/templates/olaoyejnrscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Move Goal</title>
</head>
<body>

    <div>
        <h1>Move a Goal</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Move</button>
        </form>
    </div>
    
</body>
</html>